language: scala
scala:
  - 2.11.12
dist: trusty
arch:
  - amd64
  - arm64-graviton2
virt: lxd
group: edge
jdk:
  - openjdk8
script:
  - apt-get install -y maven
  - mvn -v
  - mvn -DskipTests clean package
