language: scala
scala:
  - 2.11.12
dist: trusty
arch:
  - amd64
  - arm64-graviton2
virt: lxd
group: edge
jdk:
  - openjdk8
script:
  - cd /opt
  - wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - export PATH=$PATH:/opt/apache-maven-3*/bin
  - mvn -v
  - mvn -DskipTests clean package
